import Navigation from "@/components/global/Navigation";
import type { Metadata } from "next";
import "./globals.css";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";
import NavigationBeforeAuth from "@/components/global/NavigationBeforeAuth";

export const metadata: Metadata = {
    title: {
        template: "%s | My Body Buddy",
        default: "My Body Buddy",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <header>
                        <SignedOut>
                            <NavigationBeforeAuth />
                        </SignedOut>
                    </header>
                    <SignedIn>
                        <Navigation />
                        <UserButton />
                    </SignedIn>
                    <main>{children}</main>
                </body>
            </html>
        </ClerkProvider>
    );
}
