import Navigation from "@/components/global/Navigation";
import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: {
    template: "%s | My Body Buddy",
    default: "My Body Buddy",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
